app:
  base_path: '/msheeks/brewstack/web'
database:
  enabled: false
  host: 'dev.labsix.co'
  user: 'homebrew'
  pass: 'EPBVW48RrTySsmWG'
  schema: 'homebrew'
  prefix: ''
commands:
  database:
    migrate:
      class: Homebrew\Database\Driver
      method: migrate